INSERT INTO series (title, author_id, subgenre_id) VALUES ("Okay",1,1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("Second",2,2);
INSERT INTO subgenres (name) VALUES ("Sci-fi");
INSERT INTO subgenres (name) VALUES ("Fantasy");
INSERT INTO authors (name) VALUES ("George");
INSERT INTO authors (name) VALUES ("Martin");
INSERT INTO books (title, year, series_id) VALUES ("THe first", 2002, 1);
INSERT INTO books (title, year, series_id) VALUES ("The second",2003, 2);
INSERT INTO books (title, year, series_id) VALUES ("The third",2004,1);
INSERT INTO books (title, year, series_id) VALUES ("The fourth",2006,2);
INSERT INTO books (title, year, series_id) VALUES ("The fifth",2005,1);
INSERT INTO books (title, year, series_id) VALUES ("The Sixth",2007,2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Tom","KISS","Human",1,1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Tom","KISS","Human",2,2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Tom","KISS","Human",1,1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Tom","KISS","Human",2,2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Tom","KISS","Human",1,1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Tom","KISS","Human",2,2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Tom","KISS","Human",1,1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Tom","KISS","Human",2,2);
INSERT INTO character_books(book_id, character_id) VALUES (1,1);
INSERT INTO character_books(book_id, character_id) VALUES (2,1);
INSERT INTO character_books(book_id, character_id) VALUES (3,1);
INSERT INTO character_books(book_id, character_id) VALUES (1,2);
INSERT INTO character_books(book_id, character_id) VALUES (2,2);
INSERT INTO character_books(book_id, character_id) VALUES (3,2);
INSERT INTO character_books(book_id, character_id) VALUES (2,3);
INSERT INTO character_books(book_id, character_id) VALUES (3,4);
INSERT INTO character_books(book_id, character_id) VALUES (5,5);
INSERT INTO character_books(book_id, character_id) VALUES (6,5);
INSERT INTO character_books(book_id, character_id) VALUES (7,5);
INSERT INTO character_books(book_id, character_id) VALUES (5,6);
INSERT INTO character_books(book_id, character_id) VALUES (6,6);
INSERT INTO character_books(book_id, character_id) VALUES (6,7);
INSERT INTO character_books(book_id, character_id) VALUES (5,8);
INSERT INTO character_books(book_id, character_id) VALUES (7,9);
